-- 预先创建好数据库
-- create database straw_test

@model`DropTable`
DROP TABLE IF EXISTS :TBNAME;

@model`CreateUserTable`
CREATE TABLE IF NOT EXISTS USER (
    ID INT(10) NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(200) NULL DEFAULT NULL COLLATE utf8mb4_0900_ai_ci,
    USERDESC TEXT NULL DEFAULT NULL COLLATE utf8mb4_0900_ai_ci,
    VALID INT(10) NULL DEFAULT '1',
    CREATEBY VARCHAR(200) NULL DEFAULT NULL COLLATE utf8mb4_0900_ai_ci,
    CREATETIME DATETIME NULL DEFAULT NULL,
    UPDATEBY VARCHAR(200) NULL DEFAULT NULL COLLATE utf8mb4_0900_ai_ci,
    UPDATETIME DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (ID) USING BTREE
)
COLLATE=utf8mb4_0900_ai_ci
ENGINE=InnoDB
;

@model`CreateClientTable`
CREATE TABLE IF NOT EXISTS CLIENT (
    ID INT(10) NOT NULL AUTO_INCREMENT,
    USERID BIGINT(19) NULL DEFAULT NULL COLLATE utf8mb4_0900_ai_ci,
    PHONE VARCHAR(16) NULL DEFAULT NULL COLLATE utf8mb4_0900_ai_ci,
    VALID INT(10) NULL DEFAULT '1',
    CREATEBY VARCHAR(200) NULL DEFAULT NULL COLLATE utf8mb4_0900_ai_ci,
    CREATETIME DATETIME NULL DEFAULT NULL,
    UPDATEBY VARCHAR(200) NULL DEFAULT NULL COLLATE utf8mb4_0900_ai_ci,
    UPDATETIME DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (ID) USING BTREE
)
COLLATE=utf8mb4_0900_ai_ci
ENGINE=InnoDB
;

@model`TruncateTable`
TRUNCATE :TBNAME;

@model`InsertUser`
INSERT INTO USER(NAME,USERDESC,CREATEBY,CREATETIME,UPDATEBY,UPDATETIME)
VALUES (:NAME,:USERDESC,:CREATEBY,:CREATETIME,:UPDATEBY,:UPDATETIME);

@model`InsertClient`
INSERT INTO CLIENT(USERID,PHONE,CREATEBY,CREATETIME,UPDATEBY,UPDATETIME)
VALUES (:USERID,:PHONE,:CREATEBY,:CREATETIME,:UPDATEBY,:UPDATETIME);