-- 预先创建好数据库
-- create database straw_test

@model(DropTable)
DROP TABLE IF EXISTS :TBNAME;

@model(CreateUserTable)
CREATE TABLE IF NOT EXISTS `USER` (
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `DESC` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `VALID` INT(10) NULL DEFAULT '1',
    `CREATEBY` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `CREATE` DATETIME NULL DEFAULT NULL,
    `UPDATEBY` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `UPDATE` DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;

@model(CreateClientTable)
CREATE TABLE IF NOT EXISTS `CLIENT` (
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
    `USERID` BIGINT(19) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `PHONE` VARCHAR(16) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `VALID` INT(10) NULL DEFAULT '1',
    `CREATEBY` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `CREATE` DATETIME NULL DEFAULT NULL,
    `UPDATEBY` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `UPDATE` DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;

@model(TruncateTable)
TRUNCATE :TBNAME;

@model(InsertUser)
INSERT INTO USER(NAME,DESC,CREATEBY,CREATE,UPDATEBY,UPDATE)
VALUES (:NAME,:DESC,:CREATEBY,:CREATE,:UPDATEBY,:UPDATE);

@model(InsertClient)
INSERT INTO USER(USERID,PHONE,CREATEBY,CREATE,UPDATEBY,UPDATE)
VALUES (:USERID,:PHONE,:CREATEBY,:CREATE,:UPDATEBY,:UPDATE);