-- 预先创建好数据库
-- create database straw_test

@model`DropTable`
DROP TABLE IF EXISTS :TBNAME;

@model`CreateUserTable`
CREATE TABLE IF NOT EXISTS "USER" (
    ID INTEGER NOT NULL,
    NAME VARCHAR(200) NULL DEFAULT NULL,
    USERDESC TEXT NULL DEFAULT NULL,
    VALID INTEGER NULL DEFAULT '1',
    CREATEBY VARCHAR(200) NULL DEFAULT NULL,
    CREATETIME TIMESTAMP NULL DEFAULT NULL,
    UPDATEBY VARCHAR(200) NULL DEFAULT NULL,
    UPDATETIME TIMESTAMP NULL DEFAULT NULL
);

@model`CreateClientTable`
CREATE TABLE IF NOT EXISTS "CLIENT" (
    ID INTEGER NOT NULL,
    USERID INTEGER NULL DEFAULT NULL,
    PHONE VARCHAR(16) NULL DEFAULT NULL,
    VALID INTEGER NULL DEFAULT '1',
    CREATEBY VARCHAR(200) NULL DEFAULT NULL,
    CREATETIME TIMESTAMP NULL DEFAULT NULL,
    UPDATEBY VARCHAR(200) NULL DEFAULT NULL,
    UPDATETIME TIMESTAMP NULL DEFAULT NULL
);

@model`TruncateTable`
TRUNCATE :TBNAME;

@model`InsertUser`
INSERT INTO USER(NAME,USERDESC,CREATEBY,CREATETIME,UPDATEBY,UPDATETIME)
VALUES (:NAME,:USERDESC,:CREATEBY,:CREATETIME,:UPDATEBY,:UPDATETIME);

@model`InsertClient`
INSERT INTO USER(USERID,PHONE,CREATEBY,CREATETIME,UPDATEBY,UPDATETIME)
VALUES (:USERID,:PHONE,:CREATEBY,:CREATETIME,:UPDATEBY,:UPDATETIME);